### ISSUE TITLE
Failes to compile on Ubuntu 14.04 - branch: c-node

### ISSUE THREAD

**Issue by f34nk** [Overbryd/myhtmlex#4]
Ubuntu 14.04
Erlang/OTP 20 [erts-9.2]
gcc version 4.8.5
**branch: c-node**

Running the task `mix compile` returns with error:
>undefined reference to 'erl_init'
undefined reference to 'pthread_create'

According to this [post](https://stackoverflow.com/a/14186556):
>Newest versions of the GNU toolchain require that the object files and libraries be specified in the same order their symbols depend on each other. So you should generally put the library flags to the end of the invocation

Making these changes to the Makefile fixes the problem on my side: 
- adding pthread link to the MYHTMLEX_CFLAGS
- moving CNODE_CFLAGS to the end of the cclient command

```
diff --git a/Makefile b/Makefile
index 8848d71..8662ce6 100644
--- a/Makefile
+++ b/Makefile
@@ -25,6 +25,7 @@ MYHTMLEX_CFLAGS += -I$(ERLANG_PATH)/include
 MYHTML_PATH = c_src/myhtml
 MYHTML_STATIC = $(MYHTML_PATH)/lib/libmyhtml_static.a
 MYHTMLEX_CFLAGS += -I$(MYHTML_PATH)/include
+MYHTMLEX_CFLAGS += -lpthread
 
 # that would be used for a dynamically linked build
 # MYHTMLEX_CFLAGS += -L$(MYHTML_PATH)/lib
@@ -58,7 +59,7 @@ priv/myhtmlex.so: c_src/myhtmlex.c $(MYHTML_STATIC)
        $(CC) $(MYHTMLEX_CFLAGS) $(MYHTMLEX_LDFLAGS) -o $@ $< $(MYHTML_STATIC)
 
 priv/cclient: c_src/cclient.c $(MYHTML_STATIC)
-       $(CC) $(CNODE_CFLAGS) -o $@ $< $(MYHTML_STATIC)
+       $(CC) -o $@ $< $(MYHTML_STATIC) $(CNODE_CFLAGS)
```

Frank

**Comment by Overbryd** [comment]
Thank you for reporting that issue.

~~I have now removed the `c_src/cserver.c`, that is no longer worth pursuing. So the `pthread` thing should be gone.~~

The changes are there, plus I added a Ubuntu 14.04 in `build-tests/`.
I have not had the chance to run it yet (my docker setup locally was out of service).

But I pushed the changes anyway so you could have a look.
If you see something not working on your machine, please adapt the docker build test in `build-tests/` so I can reproduce the error here.

Please close if you are content with the changes.

**Comment by f34nk** [comment]
Everything works. Thank you
